WITH CUST_MONTH AS  
    (SELECT DISTINCT CUST_CODE, DATE_TRUNC(PARSE_DATE('%Y%m%d', CAST(SHOP_DATE AS STRING)), MONTH) SHOP_MONTH 
    FROM `certain-torus-332501.BADS7105.SuperMarket` 
    WHERE CUST_CODE IS NOT NULL ) 

SELECT REPORT_MONTH ,
    COUNT(DISTINCT CASE WHEN STATUS = 'NEW' THEN CUST_CODE ELSE NULL END) AS New_Customer ,
    COUNT(DISTINCT CASE WHEN STATUS = 'REPEAT' THEN CUST_CODE ELSE NULL END) AS Repeat_Customer ,
    COUNT(DISTINCT CASE WHEN STATUS = 'REACTIVATED' THEN CUST_CODE ELSE NULL END) AS Reactivated_Customer ,
    -COUNT(DISTINCT CASE WHEN STATUS = 'CHURNED' THEN CUST_CODE ELSE NULL END) AS Churned_Customer,
    COUNT(STATUS != 'CHURNED') AS CUSTOMER_REMAIN
FROM  
    (SELECT CUST_CODE, SHOP_MONTH AS REPORT_MONTH, PREV_MONTH ,
      CASE 
        WHEN DATE_DIFF(SHOP_MONTH, PREV_MONTH, MONTH) IS NULL THEN 'NEW' 
        WHEN DATE_DIFF(SHOP_MONTH, PREV_MONTH, MONTH) = 1 THEN 'REPEAT' 
        WHEN DATE_DIFF(SHOP_MONTH, PREV_MONTH, MONTH) > 1 THEN 'REACTIVATED' 
      ELSE NULL END AS STATUS 
    FROM 
        (SELECT CUST_CODE, SHOP_MONTH, LAG(SHOP_MONTH, 1) OVER (PARTITION BY CUST_CODE ORDER BY SHOP_MONTH) AS PREV_MONTH 
         FROM CUST_MONTH ) 
        UNION ALL 
        SELECT CUST_CODE, DATE_ADD(SHOP_MONTH, INTERVAL 1 MONTH) REPORT_MONTH, SHOP_MONTH as PREV_MONTH ,'CHURNED' AS STATUS 
        FROM  
            (SELECT CUST_CODE, SHOP_MONTH ,
                LEAD(SHOP_MONTH, 1) OVER (PARTITION BY CUST_CODE ORDER BY SHOP_MONTH) AS NEXT_TRANS_DATE ,
                DATE_DIFF(LEAD(SHOP_MONTH, 1) OVER (PARTITION BY CUST_CODE ORDER BY SHOP_MONTH), SHOP_MONTH, MONTH) AS N_MONTH 
            FROM CUST_MONTH ) 
            WHERE (N_MONTH > 1 or N_MONTH is null) AND SHOP_MONTH < (SELECT MAX(SHOP_MONTH) FROM CUST_MONTH) ) 
GROUP BY REPORT_MONTH 
ORDER BY REPORT_MONTH ; 